default:
  statusbar: false
  browser_spellcheck: true
  convert_urls: false
  height: "200"
  menubar: false
  plugins: "autolink paste fullscreen link anchor lists hr searchreplace"
  toolbar_items_size: 'small'
  toolbar1: "cut copy paste searchreplace | undo redo | removeformat | fullscreen code"
  toolbar2: "bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | link unlink | hr"
  paste_auto_cleanup_on_paste: true
  paste_remove_spans: true
  paste_strip_class_attributes: 'mso'
  content_css: /css/tinymce.css
